global class Constants {
    // Used in get_all_details_under_enrollment
    public static final string SESSION_STATUS_SCHEDULED = 'SCHEDULED';
    public static final string SESSION_STATUS_COMPLETED = 'COMPLETED';
    public static final string SESSION_ATTACHMENT_TYPE_NOTE = 'NOTE';
    public static final string SESSION_ATTACHMENT_TYPE_ASSESSMENT = 'ASSESSMENT';
    public static final string Mentor_CE_Status_Requested = 'Requested by Mentor';
    public static final string Mentor_CE_Status_Scheduled = 'Sessions Scheduled';
    public static final string GENERIC_TEST_MASTER = 'Generic';
    public static final string STA_STATUS_PENDING = 'Pending';
}